//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Speedo.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Speedo.Languages.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are awesome.
        /// </summary>
        public static string About_AwesomeButton {
            get {
                return ResourceManager.GetString("About_AwesomeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How awesome?.
        /// </summary>
        public static string About_AwesomeCaption {
            get {
                return ResourceManager.GetString("About_AwesomeCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very awesome..
        /// </summary>
        public static string About_AwesomeMessage {
            get {
                return ResourceManager.GetString("About_AwesomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Made by.
        /// </summary>
        public static string About_MadeBy {
            get {
                return ResourceManager.GetString("About_MadeBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy policy.
        /// </summary>
        public static string About_PrivacyPolicy {
            get {
                return ResourceManager.GetString("About_PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write a review.
        /// </summary>
        public static string About_ReviewButton {
            get {
                return ResourceManager.GetString("About_ReviewButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share the love.
        /// </summary>
        public static string About_ShareTheLove {
            get {
                return ResourceManager.GetString("About_ShareTheLove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks for downloading the app! :).
        /// </summary>
        public static string About_Thanks {
            get {
                return ResourceManager.GetString("About_Thanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you enjoy using the app, please share a review in the Marketplace..
        /// </summary>
        public static string About_WriteAReview {
            get {
                return ResourceManager.GetString("About_WriteAReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string AboutMenu {
            get {
                return ResourceManager.GetString("AboutMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string AboutPageTitle {
            get {
                return ResourceManager.GetString("AboutPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accuracy warning.
        /// </summary>
        public static string AccuracyWarningCaption {
            get {
                return ResourceManager.GetString("AccuracyWarningCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This software uses GPS signals to calculate your speed and direction which is subject to interference and results may be skewed.
        ///
        ///The information provided can only be used as a guide..
        /// </summary>
        public static string AccuracyWarningMessage {
            get {
                return ResourceManager.GetString("AccuracyWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speedo Plus.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E.
        /// </summary>
        public static string Direction_East {
            get {
                return ResourceManager.GetString("Direction_East", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N.
        /// </summary>
        public static string Direction_North {
            get {
                return ResourceManager.GetString("Direction_North", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NE.
        /// </summary>
        public static string Direction_NorthEast {
            get {
                return ResourceManager.GetString("Direction_NorthEast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NW.
        /// </summary>
        public static string Direction_NorthWest {
            get {
                return ResourceManager.GetString("Direction_NorthWest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S.
        /// </summary>
        public static string Direction_South {
            get {
                return ResourceManager.GetString("Direction_South", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SE.
        /// </summary>
        public static string Direction_SouthEast {
            get {
                return ResourceManager.GetString("Direction_SouthEast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SW.
        /// </summary>
        public static string Direction_SouthWest {
            get {
                return ResourceManager.GetString("Direction_SouthWest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W.
        /// </summary>
        public static string Direction_West {
            get {
                return ResourceManager.GetString("Direction_West", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to distance.
        /// </summary>
        public static string DistanceDisplay {
            get {
                return ResourceManager.GetString("DistanceDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable speed alert.
        /// </summary>
        public static string EnableSpeedAlertButton {
            get {
                return ResourceManager.GetString("EnableSpeedAlertButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to location inaccessible.
        /// </summary>
        public static string GpsStatus_Inaccessible {
            get {
                return ResourceManager.GetString("GpsStatus_Inaccessible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPS initializing.
        /// </summary>
        public static string GpsStatus_Initializing {
            get {
                return ResourceManager.GetString("GpsStatus_Initializing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string GpsStatus_Normal {
            get {
                return ResourceManager.GetString("GpsStatus_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPS not available.
        /// </summary>
        public static string GpsStatus_Unavailable {
            get {
                return ResourceManager.GetString("GpsStatus_Unavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to weak GPS signal.
        /// </summary>
        public static string GpsStatus_Weak {
            get {
                return ResourceManager.GetString("GpsStatus_Weak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable location.
        /// </summary>
        public static string LocationDisableWarningCaption {
            get {
                return ResourceManager.GetString("LocationDisableWarningCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application will not work without location access. Are you sure you still want to disable it?.
        /// </summary>
        public static string LocationDisableWarningMessage {
            get {
                return ResourceManager.GetString("LocationDisableWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location policy statement.
        /// </summary>
        public static string PrivacyPolicyCaption {
            get {
                return ResourceManager.GetString("PrivacyPolicyCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This software temporarily stores and uses your location data for the purpose of calculating speed and direction.
        ///
        ///Your location may be sent to Bing over the internet to position the map..
        /// </summary>
        public static string PrivacyPolicyMessage {
            get {
                return ResourceManager.GetString("PrivacyPolicyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set maximum speed to trigger audible alert.
        /// </summary>
        public static string SetSpeedAlert {
            get {
                return ResourceManager.GetString("SetSpeedAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re going too fast!.
        /// </summary>
        public static string SpeechAlert {
            get {
                return ResourceManager.GetString("SpeechAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound.
        /// </summary>
        public static string SpeedAlert_Sound {
            get {
                return ResourceManager.GetString("SpeedAlert_Sound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voice.
        /// </summary>
        public static string SpeedAlert_Voice {
            get {
                return ResourceManager.GetString("SpeedAlert_Voice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert type:.
        /// </summary>
        public static string SpeedAlertType {
            get {
                return ResourceManager.GetString("SpeedAlertType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to average.
        /// </summary>
        public static string SpeedAverage {
            get {
                return ResourceManager.GetString("SpeedAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to max.
        /// </summary>
        public static string SpeedMax {
            get {
                return ResourceManager.GetString("SpeedMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kmh.
        /// </summary>
        public static string SpeedUnit_Kilometers {
            get {
                return ResourceManager.GetString("SpeedUnit_Kilometers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mph.
        /// </summary>
        public static string SpeedUnit_Miles {
            get {
                return ResourceManager.GetString("SpeedUnit_Miles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enable location access.
        /// </summary>
        public static string SwitchLocationMenu_Disabled {
            get {
                return ResourceManager.GetString("SwitchLocationMenu_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to disable location access.
        /// </summary>
        public static string SwitchLocationMenu_Enabled {
            get {
                return ResourceManager.GetString("SwitchLocationMenu_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to switch to imperial (mph).
        /// </summary>
        public static string SwitchUnitMenu_Kilometers {
            get {
                return ResourceManager.GetString("SwitchUnitMenu_Kilometers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to switch to metric (km/h).
        /// </summary>
        public static string SwitchUnitMenu_Miles {
            get {
                return ResourceManager.GetString("SwitchUnitMenu_Miles", resourceCulture);
            }
        }
    }
}
